### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by PrtyBlk** [tomasff/BeesPlus#1]
[fr.txt](https://github.com/tomasff/BeesPlus/files/4577368/fr.txt)

It required me to make it a .txt to upload instead of the .yml it's suppose to be sorry about that.

**Comment by tomasff** [comment]
Hi there, thank you for your contribution.

This will be included in the next updated

**Comment by tomasff** [comment]
Issue solved. Translation released in version 1.4.3-SNAPSHOT.
